### ISSUE TITLE
Thanks for sharing! Could you please complete the remaining code？

### ISSUE THREAD

**Issue by SymbolZH** [tengxiaoliu/XoT#1]
Thank you for sharing this outstanding work!
However, the code in the repository seems to be missing parts of the requirements.txt and utils folders. Meanwhile, I did not see analyze. py in the src folder. 
Could you please also share these codes?

**Comment by tengxiaoliu** [comment]
Thank you for your interest in our work!
We plan to organize and upload the rest of the code within this week. Stay tuned!
